bo = input('digite algo: ')
print('o tipo primitivo desse valor é', type(bo))
print('só tem espaço?', bo.isspace())
print('só tem numero?', bo.isnumeric())
print('só tem alfabeto?', bo.isalpha())
print('é alfanumerico?', bo.isalnum())
print('esta maiusculo?', bo.isupper())
print('esta minusculo?', bo.islower())
print('esta capitalizado?', bo.istitle())